drajer-health/eCRNow

src/main/java/com/drajer/cda/utils/CdaValidatorUtil.java
src/main/java/com/drajer/cda/utils/ValidateErrorHandler.java
src/main/java/com/drajer/eca/model/ActionRepo.java
src/main/java/com/drajer/eca/model/CloseOutEicrAction.java
src/main/java/com/drajer/eca/model/CreateEicrAction.java
src/main/java/com/drajer/eca/model/ValidateEicrAction.java
src/main/java/com/drajer/ecrapp/service/WorkflowService.java
src/main/resources/application.properties

Added support to validate eICR XML file against XSD.

Added support to validate eICR XML file 

---

src/main/java/com/drajer/cda/utils/CdaGeneratorConstants.java

updated getCodeSystemFromUrl method to return Pair values from map

updated getCodeSystemFromUrl method to return Pair values from map

---

src/main/java/com/drajer/cdafromr4/CdaHeaderGenerator.java
src/main/java/com/drajer/eca/model/ActionRepo.java
src/main/java/com/drajer/eca/model/SubmitEicrAction.java
src/main/java/com/drajer/ecrapp/service/WorkflowService.java
src/main/java/com/drajer/routing/RestApiSender.java
src/main/java/com/drajer/sof/launch/RRReceiverController.java
src/main/java/com/drajer/sof/service/LoadingQueryR4Bundle.java
src/main/java/com/drajer/sof/utils/FhirContextInitializer.java
src/test/java/com/drajer/ecr/it/ITSystemLaunchAllActions.java
src/test/java/com/drajer/ecr/it/common/BaseIntegrationTest.java
src/test/java/com/drajer/test/Assertion/AssertCdaElement.java
src/test/java/com/drajer/test/util/EICRValidator.java
src/test/java/com/drajer/test/util/FhirR4Utils.java
src/test/java/com/drajer/test/util/TestUtils.java
src/test/java/com/drajer/test/util/ValidationUtils.java
src/test/java/com/drajer/test/util/ValueSetMapping.java
src/test/resources/R4/Misc/ClientDetails/ClientDataEntry1.json
src/test/resources/TestSystemLaunch.yaml

Wireup RestApi to submiteisr action.
Null check for guardian
Tests for Immunization section.

Cerner rest api sender

---

frontend/package-lock.json
src/main/java/com/drajer/cdafromdstu2/Dstu2CdaHeaderGenerator.java
src/main/java/com/drajer/cdafromr4/CdaHeaderGenerator.java
src/main/java/com/drajer/ecrapp/dao/EicrDao.java
src/main/java/com/drajer/ecrapp/dao/impl/EicrDaoImpl.java
src/main/java/com/drajer/sof/launch/LaunchController.java
src/main/java/com/drajer/sof/model/LaunchDetails.java
src/test/resources/R4/Misc/LaunchDetails/LaunchDataEntry1.json
src/test/resources/R4/Misc/LaunchDetails/LaunchDetails.json
src/test/resources/R4/Misc/LaunchDetails/LaunchDetails_Without_Encounter.json
src/test/resources/launchDetails.json

Updated SetId to Integer and implemented method to return Max SetId

Document ref impl

---

src/main/java/com/drajer/routing/impl/DirectResponseReceiver.java
src/main/java/com/drajer/sof/launch/LaunchController.java
src/main/java/com/drajer/sof/model/ClientDetails.java

Modified code to fix #87 and #89 issues

Modified code to fix #87 and #89 issues

---

frontend/src/Views/ClientDetails/ClientDetails.js
src/main/java/com/drajer/routing/impl/DirectResponseReceiver.java
src/main/java/com/drajer/sof/model/ClientDetails.java
src/main/java/com/drajer/sof/utils/QueryConstants.java
src/main/java/com/drajer/sof/utils/R4ResourcesData.java

Fixed issues in updating the client details

Fixed issues in updating the client details

---

src/main/java/com/drajer/ecrapp/util/ApplicationUtils.java
src/main/java/com/drajer/routing/impl/DirectResponseReceiver.java

Fixed Path Manipulation issue

---

src/main/java/com/drajer/routing/impl/DirectResponseReceiver.java

Changed from imap to IMAPS

---

src/main/java/com/drajer/ecrapp/util/ApplicationUtils.java
src/main/java/com/drajer/routing/impl/DirectResponseReceiver.java

Added UUID to use with the filename

Added UUID to use with the filename

---

src/main/java/com/drajer/ecrapp/security/AESEncryption.java

Fixed AESEncryption issues

---

src/main/java/com/drajer/sof/launch/RRReceiverController.java
src/main/java/com/drajer/sof/service/impl/RRReceiverServiceImpl.java

Updates to DocumentReference Submission

Updates to DocumentReference Submission

---

src/test/java/com/drajer/sof/utils/RefreshTokenSchedulerTest.java

Fixed build failure issue

---

README.md

- And fix typo in `# 2.2 ERSD Module: ##`, TThis --> This.

README.md: Update urls to HTTPS

---

sample-ehr/src/main/java/com/drajer/sampleehr/controller/AuthorizationEndpoint.java
src/main/java/com/drajer/eca/model/CloseOutEicrAction.java
src/main/java/com/drajer/eca/model/CreateEicrAction.java
src/main/java/com/drajer/eca/model/PeriodicUpdateEicrAction.java
src/main/java/com/drajer/ecrapp/model/ScheduledTasks.java
src/main/java/com/drajer/sof/utils/R4ResourcesData.java
src/test/java/com/drajer/cdafromr4/CdaFhirUtilitiesTest.java
src/test/java/com/drajer/test/ITRRReceiverServiceController.java
src/test/java/com/drajer/test/ITSystemLaunch.java
src/test/java/com/drajer/test/ITSystemLaunchAllActions.java
src/test/java/com/drajer/test/ITValidateEicrDoc.java
src/test/java/com/drajer/test/util/TestUtils.java
src/test/java/com/drajer/test/util/ValueSetMapping.java

Fixed SonarQube issues

---

src/main/java/com/drajer/ecrapp/security/AESEncryption.java
src/main/java/com/drajer/ecrapp/util/CryptoUtils.java
src/main/java/com/drajer/sof/launch/LaunchController.java
src/main/java/com/drajer/sof/model/LaunchDetails.java
src/main/java/com/drajer/sof/model/SystemLaunch.java
src/test/java/com/drajer/sof/dao/impl/LaunchDetailsDaoTest.java
src/test/resources/R4/Misc/LaunchDetails/LaunchDetails.json

Fixed Security Vulnerability issues and added new columns in launchdetails table.

Fix sonar q issues

---

src/test/java/com/drajer/test/ITSystemLaunchAllActions.java
src/test/resources/test-yaml/encounterSection.yaml

Fix test case failures

---

src/main/java/com/drajer/sof/model/R4FhirData.java
src/main/java/com/drajer/sof/utils/R4ResourcesData.java

Updated code to filter Conditions

Updated code to filter Conditions

---

src/main/java/com/drajer/sof/launch/LaunchController.java
src/main/java/com/drajer/sof/model/LaunchDetails.java
src/main/java/com/drajer/sof/utils/R4ResourcesData.java
src/main/java/com/drajer/sof/utils/RefreshTokenScheduler.java
src/test/java/com/drajer/test/ITSystemLaunchAllActions.java
src/test/resources/R4/Condition/ConditionBundle_d2572364249.json
src/test/resources/R4/Condition/ConditionWithAndWithoutTriggerCodes.json
src/test/resources/R4/Condition/ConditionWithTwoTriggerCodes.json
src/test/resources/R4/Condition/Condition_FilterByDtTm.json
src/test/resources/test-yaml/historyOfPresentIllnessSection.yaml
src/test/resources/test-yaml/loadingQueryServiceTest.yaml
src/test/resources/test-yaml/problemSection.yaml
src/test/resources/test-yaml/triggerQueryServiceTest.yaml

Updated code to filter Pregnancy conditions

Updated code to filter Pregnancy conditions

---

src/test/resources/test-yaml/headerSection.yaml

Fixed Test case failure

---

src/main/java/com/drajer/ecrapp/service/impl/EicrServiceImpl.java
src/main/java/com/drajer/sof/utils/R4ResourcesData.java

Saving DocRefId in eicr table after posting DocRef to EHR

Fix test case

---

src/main/java/com/drajer/sof/utils/FhirContextInitializer.java
src/test/resources/R4/Observation/ObservationEnd.json
src/test/resources/R4/Observation/ObservationStart.json
src/test/resources/test-yaml/loadingQueryServiceTest.yaml
src/test/resources/test-yaml/resultSection.yaml
src/test/resources/test-yaml/triggerQueryServiceTest.yaml

Updated code to get all the records when there are multiple pages in Bundle

Updated code to get all the records when there are multiple Pages in

---

src/main/java/com/drajer/ecrapp/controller/EicrController.java
src/main/java/com/drajer/ecrapp/dao/EicrDao.java
src/main/java/com/drajer/ecrapp/dao/impl/EicrDaoImpl.java
src/main/java/com/drajer/ecrapp/service/EicrRRService.java
src/main/java/com/drajer/ecrapp/service/impl/EicrServiceImpl.java
src/main/java/com/drajer/sof/launch/RRReceiverController.java
src/test/java/com/drajer/ecrapp/dao/impl/EicrDaoTest.java
src/test/java/com/drajer/test/ITRRReceiverServiceController.java

Implemented API to get EICR and RR data by X-Request-Id

Implemented API to get EICR and RR data by X-Request-Id

---

src/test/java/com/drajer/test/ITRRReceiverServiceController.java

Fixed build issue

---

src/test/java/com/drajer/cda/utils/CdaGeneratorConstantsTest.java
src/test/java/com/drajer/cda/utils/CdaGeneratorUtilsTest.java
src/test/java/com/drajer/cdafromr4/CdaFhirUtilitiesTest.java
src/test/resources/R4/Misc/FhirToCDAMappedCodes.json

Implement new test cases

---

src/main/java/com/drajer/sof/launch/LaunchController.java

Scheduling the Job after launching the application using Encounter

Updates to scheduling jobs

---

pom.xml
src/main/java/com/drajer/bsa/kar/condition/FhirPathProcessor.java
src/main/java/com/drajer/cdafromr4/CdaMedicationGenerator.java

* Update to HAPI 5.4
* Exclude Java EE from the evaluator depedencies

Add cql evaluator, update to HAPI 5.4

---

pom.xml
src/main/java/com/drajer/bsa/kar/action/EvaluateMeasure.java
src/main/java/com/drajer/bsa/service/impl/KarParserImpl.java

* Change the Measure artifact to reflect the latest changes in the evaluator project

Fix compilation issues with Measure processor

---

src/main/java/com/drajer/bsa/ehr/service/impl/EhrFhirR4QueryServiceImpl.java
src/main/java/com/drajer/bsa/kar/action/EvaluateMeasure.java
src/main/java/com/drajer/bsa/kar/action/SubmitReport.java
src/main/java/com/drajer/bsa/kar/model/BsaAction.java
src/main/java/com/drajer/bsa/kar/model/BsaRelatedAction.java
src/main/java/com/drajer/bsa/service/impl/KarParserImpl.java

The PR adds a bit of logging for Measure evaluation, and adds additional context for PlanDefinition actions, 
(Also, it notes that there's a potential bug on line 108 of EhrFhirR4QueryServiceImpl.java)

Add Plan Definition context for actions

---

src/main/java/com/drajer/eca/model/CloseOutEicrAction.java
src/main/java/com/drajer/eca/model/CreateEicrAction.java
src/main/java/com/drajer/eca/model/PeriodicUpdateEicrAction.java
src/main/java/com/drajer/ecrapp/config/TaskConfiguration.java
src/main/java/com/drajer/ecrapp/controller/SchedulerController.java
src/main/java/com/drajer/ecrapp/dao/SchedulerDao.java
src/main/java/com/drajer/ecrapp/dao/impl/SchedulerDaoImpl.java
src/main/java/com/drajer/ecrapp/model/ScheduledTasks.java
src/main/java/com/drajer/ecrapp/service/SchedulerService.java
src/main/java/com/drajer/ecrapp/service/WorkflowService.java
src/main/java/com/drajer/ecrapp/service/impl/ScheduledServiceImpl.java
src/main/java/com/drajer/sof/launch/SimulatorController.java
src/main/resources/application.properties
src/test/java/com/drajer/test/ITSystemLaunchAllActions.java

Implemented Rest API to receive EICR
Implemented Search API to get Scheduled tasks

Rest api receiver impl

---

pom.xml
src/main/java/com/drajer/ecrapp/config/ValueSetSingleton.java

Fixes for #238 and Full ECR defect leading to intermittent unit test failures.

Fix full eCR Issue with MatchTriggerCodes.

---

src/main/java/com/drajer/ecrapp/service/WorkflowService.java
src/main/java/com/drajer/sof/service/LoadingQueryR4Bundle.java
src/main/java/com/drajer/sof/utils/R4ResourcesData.java
src/test/resources/test-yaml/triggerQueryServiceTest.yaml

Remove Practitioners, Organizations, Locations, MedicationData from

Remove Practitioners, Organizations, Locations, MedicationData from

---

src/main/java/com/drajer/eca/model/CloseOutEicrAction.java
src/main/java/com/drajer/ecrapp/config/TaskConfiguration.java
src/main/java/com/drajer/sof/launch/LaunchController.java
src/main/java/com/drajer/sof/model/LaunchDetails.java

Updates for #293.

---

src/main/java/com/drajer/cda/utils/CdaGeneratorConstants.java
src/main/java/com/drajer/cdafromdstu2/Dstu2CdaFhirUtilities.java
src/main/java/com/drajer/cdafromdstu2/Dstu2CdaHeaderGenerator.java
src/main/java/com/drajer/cdafromdstu2/Dstu2CdaImmunizationGenerator.java

Dstu2 fixes for CDA generation for Allscripts

Dstu2 fixes for AllScripts

---

src/test/java/com/drajer/ecrapp/dao/impl/PhMessageDaoTest.java
src/test/resources/ecrTestData/phMessageInput/searchParam.json

PhMessageDao test cases have been added.
SearchParam.json's notificationId key was added

Added test cases for PhMessageDao class

---

src/test/resources/CdaTestData/Cda/sample/PatientSample.xml

junit fixes

---

src/main/resources/db-scripts/v3.1.1_to_v3.1.2_db_changes/healthcare_setting.sql
src/main/resources/db-scripts/v3.1.1_to_v3.1.2_db_changes/notification_context.sql
src/main/resources/db-scripts/v3.1.1_to_v3.1.2_db_changes/ph_messages.sql
src/main/resources/db-scripts/v3.1.1_to_v3.1.2_db_changes/scheduled_tasks.sql
src/main/resources/db-scripts/v3.1.2_to_v3.1.3_db_changes/healthcare_setting.sql
src/main/resources/db-scripts/v3.1.2_to_v3.1.3_db_changes/public_health_authority.sql
src/main/resources/db-scripts/v3.1.3_to_v3.1.4_db_changes/notification_context.sql

Apply database schema updates from versions
3.1.1 to 3.1.2
3.1.2 to 3.1.3
3.1.3 to 3.1.4

 database schema updates from versions

---

src/main/java/com/drajer/bsa/kar/action/EcrReportCreator.java
src/main/java/com/drajer/cdafromr4/CdaFhirUtilities.java
src/main/java/com/drajer/cdafromr4/CdaHeaderGenerator.java
src/test/java/com/drajer/cdafromr4/CdaFhirUtilitiesTest.java
src/test/java/com/drajer/cdafromr4/CdaHeaderGeneratorTest.java
src/test/resources/CdaTestData/Cda/Result/Result.xml

Phone" system type be prioritized over the "fax" ,"Email" "system type"

---

src/main/java/com/drajer/bsa/kar/action/HcsReportCreator.java
src/main/java/com/drajer/fhirecr/FhirGeneratorConstants.java

The following resources is not being added to the Resources for the Bundle.
- Careteam
- Careplan
- Goal
HcsReportCreator updated to add the above resources.

Careteam, Careplan and Goal Resources not being added in HcsReportCreator

---

src/main/java/com/drajer/bsa/utils/R3ToR2DataConverterUtils.java
src/main/java/com/drajer/cda/utils/CdaGeneratorConstants.java
src/main/java/com/drajer/cda/utils/CdaGeneratorUtils.java
src/main/java/com/drajer/cdafromr4/CdaBodyGenerator.java
src/main/java/com/drajer/cdafromr4/CdaFhirUtilities.java
src/main/java/com/drajer/cdafromr4/CdaOdhDataGenerator.java
src/main/java/com/drajer/cdafromr4/CdaPregnancyGenerator.java
src/main/java/com/drajer/cdafromr4/CdaProcedureGenerator.java
src/main/java/com/drajer/cdafromr4/CdaSocialHistoryGenerator.java
src/test/resources/CdaTestData/Eicr/eicr.xml

Updates to 3.1.6

---

docker-compose.yml
pom.xml
src/main/java/com/drajer/ecrapp/config/SpringConfiguration.java
src/main/resources/application.properties

Cql upgrade executing tasks successfully

New cql upgrade new

---

pom.xml
src/main/java/com/drajer/bsa/ehr/service/impl/EhrFhirR4QueryServiceImpl.java
src/main/java/com/drajer/bsa/kar/action/ValidateReport.java
src/main/java/com/drajer/cdafromr4/CdaFhirUtilities.java
src/main/java/com/drajer/cdafromr4/CdaHeaderGenerator.java
src/main/java/com/drajer/cdafromr4/CdaMedicationGenerator.java
src/main/java/com/drajer/eca/model/MatchedTriggerCodes.java
src/main/java/com/drajer/ecrapp/EcrApp.java
src/main/java/com/drajer/ecrapp/config/SwaggerConfig.java
src/main/java/com/drajer/ecrapp/config/WebSecurityConfig.java
src/main/java/com/drajer/ecrapp/util/ApplicationUtils.java
src/main/resources/application.properties

Release 3.1.8

---

src/main/java/com/drajer/bsa/kar/action/ValidateReport.java
src/main/java/com/drajer/bsa/service/impl/KarParserImpl.java
src/main/java/com/drajer/bsa/service/impl/SubscriptionNotificationReceiverImpl.java
src/main/java/com/drajer/bsa/utils/SubscriptionUtils.java
src/main/java/com/drajer/cda/utils/CdaGeneratorConstants.java
src/main/java/com/drajer/cda/utils/CdaValidatorUtil.java
src/main/java/com/drajer/cdafromr4/CdaBodyGenerator.java
src/main/java/com/drajer/cdafromr4/CdaFhirUtilities.java
src/main/java/com/drajer/cdafromr4/CdaSocialHistoryGenerator.java
src/main/resources/application.properties
src/main/resources/oid-uri-mapping-r4.properties
src/test/resources/AppData/schematrons/CdaR11/CDAR2_IG_PHCASERPT_R2_STU1.1_SCHEMATRON.sch
src/test/resources/AppData/schematrons/CdaR11/voc.xml
src/test/resources/AppData/schematrons/CdaR31/CDAR2_IG_PHCASERPT_R2_D3_SCHEMATRON.sch

validations as per #848 , #849, #862.

Add schematrons from HL7 repository to help vendors implement

---

src/main/java/com/drajer/bsa/dao/impl/NotificationContextDaoImpl.java

added mutiple status search and datetime search for NotificationContext

---

src/main/java/com/drajer/bsa/dao/impl/NotificationContextDaoImpl.java

Filter by Last Updated Date: Implement filtering options to allow clients to specify a date range for notifications. This could be done by accepting startDate and endDate parameters in the API request.
Limit: Add a query parameter to limit the number of returned notifications, e.g., limit=20. This will help improve performance by restricting the result set.
Order by Last Updated: Ensure the notifications are ordered by the lastUpdated field asc

updated notification conext api

---

src/main/java/com/drajer/bsa/dao/impl/NotificationContextDaoImpl.java
src/main/java/com/drajer/ecrapp/config/SpringConfiguration.java
src/main/java/com/drajer/ecrapp/config/WebSecurityConfig.java
src/main/resources/application.properties
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.7_db_changes/notification_context.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.9_db_changes/notification_context.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.3_to_v3.1.4_db_changes/notification_context.sql

implemented getNotificationContextForReprocessing API 
added cors filter

3.1.9 build fixes

---

src/main/java/com/drajer/bsa/dao/impl/NotificationContextDaoImpl.java
src/main/resources/application.properties

updated application.properties

update date format NotificationContextDaoImpl.java

---

src/main/java/com/drajer/cda/utils/CdaGeneratorUtils.java
src/main/resources/db-scripts/msql_db_scripts/v3.1.1_to_v3.1.10_db_changes/healthcare_setting.sql
src/main/resources/db-scripts/msql_db_scripts/v3.1.1_to_v3.1.10_db_changes/kar_info.sql
src/main/resources/db-scripts/msql_db_scripts/v3.1.1_to_v3.1.10_db_changes/notification_context.sql
src/main/resources/db-scripts/msql_db_scripts/v3.1.1_to_v3.1.10_db_changes/ph_messages.sql
src/main/resources/db-scripts/msql_db_scripts/v3.1.1_to_v3.1.10_db_changes/public_health_authority.sql
src/main/resources/db-scripts/msql_db_scripts/v3.1.1_to_v3.1.10_db_changes/scheduled_tasks.sql
src/main/resources/db-scripts/msql_db_scripts/v3.1.1_to_v3.1.11_db_changes/healthcare_setting.sql
src/main/resources/db-scripts/msql_db_scripts/v3.1.1_to_v3.1.11_db_changes/kar_info.sql
src/main/resources/db-scripts/msql_db_scripts/v3.1.1_to_v3.1.11_db_changes/notification_context.sql
src/main/resources/db-scripts/msql_db_scripts/v3.1.1_to_v3.1.11_db_changes/ph_messages.sql
src/main/resources/db-scripts/msql_db_scripts/v3.1.1_to_v3.1.11_db_changes/public_health_authority.sql
src/main/resources/db-scripts/msql_db_scripts/v3.1.1_to_v3.1.11_db_changes/scheduled_tasks.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.10_db_changes/healthcare_setting.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.10_db_changes/kar_info.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.10_db_changes/notification_context.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.10_db_changes/ph_messages.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.10_db_changes/public_health_authority.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.10_db_changes/scheduled_tasks.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.11_db_changes/healthcare_setting.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.11_db_changes/kar_info.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.11_db_changes/notification_context.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.11_db_changes/ph_messages.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.11_db_changes/public_health_authority.sql
src/main/resources/db-scripts/psql_db_scripts/v3.1.1_to_v3.1.11_db_changes/scheduled_tasks.sql
src/test/resources/CdaTestData/Cda/Medication/Medication.xml
src/test/resources/CdaTestData/Cda/Medication/MedicationAdminR31.xml
src/test/resources/CdaTestData/Cda/Medication/MedicationR31.xml
src/test/resources/application-test.properties

medication fixes
logs configuration are added

db script added

---

src/main/java/com/drajer/bsa/kar/action/EcrMeasureReportCreator.java
src/main/java/com/drajer/bsa/kar/action/EcrReportCreator.java

Currently the last entry in the report bundle is a MeasureReport. 
This PR changes the last entry to a Bundle which contains the MeasureReport, as well as the evaluated resources.

Update report structure to ensure evaluated resources are bundled with MeasureReport
